In [17]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler,MaxAbsScaler,StandardScaler

In [18]:
df = [[1,2,3],[2,1,3],[5,6,10]]

In [19]:
scaler = MinMaxScaler()
scaler.fit(df)
scaler.transform(df)

array([[0.  , 0.2 , 0.  ],
       [0.25, 0.  , 0.  ],
       [1.  , 1.  , 1.  ]])

In [20]:
scaler = MaxAbsScaler()
scaler.fit_transform(df)

array([[0.2       , 0.33333333, 0.3       ],
       [0.4       , 0.16666667, 0.3       ],
       [1.        , 1.        , 1.        ]])

In [21]:
scaler = StandardScaler()
scaler.fit_transform(df)

array([[-0.98058068, -0.46291005, -0.70710678],
       [-0.39223227, -0.9258201 , -0.70710678],
       [ 1.37281295,  1.38873015,  1.41421356]])