#### 1. Import the numpy package under the name `np` (★☆☆)

In [71]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [72]:
print(np.__version__)
print(np.show_config())

1.24.3
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

#### 3. Create a null vector of size 10 (★☆☆)

In [73]:
Null = np.zeros(10)
print(Null)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [74]:
Null.nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [75]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [76]:
Null_1 = np.zeros(10)
Null_1[4] = 1
print(Null_1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [77]:
Array = np.arange(10,50)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [78]:
np.flip(Array)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [79]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [80]:
Array_2 = np.array([1,2,0,0,4,0])
np.nonzero(Array_2)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [81]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [82]:
np.empty((3,3,3))

array([[[3.47668003e-308, 0.00000000e+000, 1.12064383e-311],
        [1.12066696e-311, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 2.12199579e-314]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [83]:
Array_10_10 = np.random.randint(0,100,(10,10))
print(Array_10_10)
print(Array_10_10.max())
print(Array_10_10.min())


[[74 42 94 16 15  4 65 15 45 36]
 [52 69 56  5  9 94 51  8 24 93]
 [84 80 23 95 39 50 62 39  7 91]
 [58 31 53 88 22 40 19 58 85 32]
 [ 5 30 69 39 54 18 66 71  7 63]
 [89 94 41 99 13  8  0 46 13 75]
 [19 91 37 52 95 11 77 25 93 10]
 [36 48 78 91 67 11 69 29 70 97]
 [ 1 89 25 59 30 66 36 37 49 50]
 [74 94 50 54 58 67 57 47  5 29]]
99
0


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [84]:
RandomVector = np.random.rand(30)
print(RandomVector.mean())

0.4751332245445569


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [85]:
Border1Array = np.ones((20,20))
Border1Array[1:-1,1:-1] = 0
print(Border1Array)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [86]:
existingArray = np.random.randint(0,100,(20,20))
existingArray = np.pad(existingArray,1,'constant',constant_values=0)
print(existingArray)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 24 26 98 45 33 35 33 20 57 70 75 52 30 67 41 51 72 28 61 12  0]
 [ 0 98 49 41 94 53 90 73 87 85 95 99 55 64 16 95 93 21 20 68 62  0]
 [ 0 69 51 91 73 64 76 66  4 94 17 37 68 19 92 29 13 34 67 93 78  0]
 [ 0 35 22 43  8 37 36 46 48 63 74  9 92 62 91 21 36 65 83  3  7  0]
 [ 0 64 10 75 83 70 17 11 43 43 74 87 74 75 24 41 47 26  8 28 30  0]
 [ 0 25  2 70  6 53 67 34 50 73 20 42  1 20 36 84 30 92 35 53 65  0]
 [ 0 22 32  6 84 46 41 86 77 97 95  0 81 20 36 30 41  6 11 54 66  0]
 [ 0  0 38 89 29 22 21 64 46  5 96 93 37 44 71 42 14 10 86 18 29  0]
 [ 0 84 55 42 73 87 78  7 42 28 99 69 18 65 85 44 50 79 69 53 43  0]
 [ 0 27 29 94 11 37 96 79 43  8 96  4 19 20 57  9 44 42 56  9  9  0]
 [ 0 76 46  3 43 29 75 22 52 82 33 67  0 13 67 55 56 54  0  2 84  0]
 [ 0 10 10 24 14 93  8 80 95 84 89 22 57 38 80 93 42 39 61  1 81  0]
 [ 0 11 54 62 58  6 92 98 33 51 34  6 91 27 92 28 60 90 26 16 98  0]
 [ 0 81 68 96 25 87 17 14 94 10 89

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [87]:
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [88]:
DiagBelow = np.diag( 1+ np.arange(4) ,k=-1)
print(DiagBelow)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [89]:
CheckBoard = np.zeros((8,8),dtype=int)
CheckBoard[1::2,::2] = 1
CheckBoard[::2,1::2] = 1
print(CheckBoard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [90]:
x = 100//(7*8)
y = (100-(x*(7*8)))//8
N_Array_Var= (100-(x*(7*8)))%8

print(x,y,N_Array_Var)

1 5 4


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [91]:
base = np.array([[0,1],[1,0]])
CheckerBoard = np.tile(base,(4,4))
print(CheckerBoard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [92]:
Normal = np.random.randint(0,100,(5,5))
Normal = (Normal-Normal.mean()) / Normal.std()
print(Normal)

[[-1.06807732  0.12161276 -0.84776434  0.20973795  0.29786315]
 [-0.40713838  1.13505246 -0.53932617  0.56223872  0.87067689]
 [-0.05463762 -1.77307885 -1.02401472 -0.58338877  1.44349063]
 [-0.71557655 -0.40713838  0.43005093  1.13505246  1.26724025]
 [-1.72901625 -1.50870327  1.31130284  1.66380361  0.20973795]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [93]:
RGBA = np.dtype([("R",np.ubyte,1),("G",np.ubyte,1),("B",np.ubyte,1),("A",np.ubyte,1)])
print(RGBA)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


C:\Users\lalit\AppData\Local\Temp\ipykernel_25044\2410743269.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  RGBA = np.dtype([("R",np.ubyte,1),("G",np.ubyte,1),("B",np.ubyte,1),("A",np.ubyte,1)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [94]:
a = np.random.randint(1,10,(5,3))
b= np.random.randint(1,10,(3,2))
print(np.dot(a,b))

[[63 83]
 [68 63]
 [56 51]
 [98 83]
 [48 38]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [95]:
OneDArray = np.random.randint(1,10,(20))
OneDArray[(3 < OneDArray) & (OneDArray <= 8)] *= -1
print(OneDArray)

[-6  2 -6 -5 -8 -6 -8  2 -4  1 -6 -6  3  3  3 -8  9  2  2 -6]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [96]:
import sys
del sys.modules['numpy']
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


C:\Users\lalit\AppData\Local\Temp\ipykernel_25044\2993667357.py:4: UserWarning: The NumPy module was reloaded (imported a second time). This can in some cases result in small but subtle issues and is discouraged.
  from numpy import *


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << N_Array_Var >> 2
N_Array_Var <- N_Array_Var
1j*N_Array_Var
N_Array_Var/1/1
N_Array_Var<N_Array_Var>Z
```

In [97]:
Z= np.random.randint(1,10,(20))
# print(Z**Z)
print(2 << Z>> 2)
print(Z<- Z)
# print(1j*Z/)
print(Z/1/1)
# print(Z<Z>Z)

[ 16  32   1  16 128  64  64 128 128 256   8   2   4   1  64  16 128   4
 256  16]
[False False False False False False False False False False False False
 False False False False False False False False]
[5. 6. 1. 5. 8. 7. 7. 8. 8. 9. 4. 2. 3. 1. 7. 5. 8. 3. 9. 5.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [98]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\lalit\AppData\Local\Temp\ipykernel_25044\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\lalit\AppData\Local\Temp\ipykernel_25044\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\lalit\AppData\Local\Temp\ipykernel_25044\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [99]:
A= np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(A)),A))

[ -1.  -9.   1.  -3.   8.   3. -10.   7.   2.   7.]


#### 30. How to find common values between two arrays? (★☆☆)

In [100]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 6 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [101]:
defaults = np.seterr(all="ignore")
N_Array_Var= np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)


with np.errstate(divide='ignore'):
    N_Array_Var= np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [102]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\lalit\AppData\Local\Temp\ipykernel_25044\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [103]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday,today,tomorrow)

2024-02-19 2024-02-20 2024-02-21


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [104]:
N_Array_Var= np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

[5 6 1 5 8 7 7 8 8 9 4 2 3 1 7 5 8 3 9 5]


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [105]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [106]:
N_Array_Var= np.random.uniform(0,10,10)

print (N_Array_Var- Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

ValueError: operands could not be broadcast together with shapes (10,) (20,) 

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
N_Array_Var= np.zeros((5,5))
N_Array_Var+= np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate():
    for x in range(10):
        yield x
N_Array_Var= np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
N_Array_Var= np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
N_Array_Var= np.random.random(10)
Z.sort()
print(Z)

[2.20290989e-04 5.11402554e-02 4.11156763e-01 4.17950018e-01
 4.70504182e-01 5.00332211e-01 6.10805620e-01 6.96311117e-01
 7.13696022e-01 9.88453517e-01]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
N_Array_Var= np.arange(10)
np.add.reduce(Z)


45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
N_Array_Var= np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
N_Array_Var= np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.56744947 0.73964577 1.07985251 1.08361502 0.3897008  0.64299497
 1.03899559 0.96727775 0.92850059 1.1781965 ]
[1.39569933 0.53253995 0.43527334 0.54832132 0.94540207 0.60364152
 1.1411786  1.50753363 0.49128124 0.74768942]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
N_Array_Var= np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.         0.17451498 0.26460433 0.64025254 0.1379995  0.09707504
 0.16180436 0.60585734 0.61241907 0.32695079]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
N_Array_Var= np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
N_Array_Var= np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
N_Array_Var= np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(N_Array_Var[index])

56


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
N_Array_Var= np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),('color',    [ ('r', float, 1),('g', float, 1),('b', float, 1)])])
print(N_Array_Var)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\lalit\AppData\Local\Temp\ipykernel_25044\4272098817.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),('color',    [ ('r', float, 1),('g', float, 1),('b', float, 1)])])


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
N_Array_Var= np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

import scipy
import scipy.spatial

N_Array_Var= np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.74863289 0.28177303 0.67686117 0.65376781 0.47768111
  0.69141157 0.56354125 0.86160371 0.26456294]
 [0.74863289 0.         0.85625912 0.12213496 0.17859698 1.07786445
  0.67509598 0.47922965 0.12467467 0.59660517]
 [0.28177303 0.85625912 0.         0.75471269 0.8146573  0.22922325
  0.54028085 0.80570563 0.94755704 0.52637635]
 [0.67686117 0.12213496 0.75471269 0.         0.23647324 0.97162559
  0.55430446 0.51261154 0.19302414 0.56399923]
 [0.65376781 0.17859698 0.8146573  0.23647324 0.         1.04327254
  0.75440949 0.30105086 0.29634327 0.45789161]
 [0.47768111 1.07786445 0.22922325 0.97162559 1.04327254 0.
  0.65915104 1.02739184 1.16318495 0.73825022]
 [0.69141157 0.67509598 0.54028085 0.55430446 0.75440949 0.65915104
  0.         0.93312811 0.69752613 0.78951051]
 [0.56354125 0.47922965 0.80570563 0.51261154 0.30105086 1.02739184
  0.93312811 0.         0.59676235 0.30201745]
 [0.86160371 0.12467467 0.94755704 0.19302414 0.29634327 1.16318495
  0.69752613 0.59676

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
N_Array_Var= np.arange(10, dtype=np.float32)
N_Array_Var= Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n6,  ,  , 7, 8\n,  , 9,10,11\n""")
N_Array_Var= np.genfromtxt(s, delimiter=",", dtype=int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array N_Array_Var= [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute N_Array_Varto the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)