In [1]:
import numpy as np

In [15]:
a = np.array([[[[1,2,3,4],[1,2,3,4]],[[1,3,4,5],[6,3,3,2]]],[[[1,2,3,4],[1,2,3,4]],[[1,3,4,5],[6,3,3,2]]]])

In [17]:
a.ndim # Give the dimensions of the Object

4

In [16]:
a.size 

32

In [18]:
a.shape

(2, 2, 2, 4)

In [19]:
l = [1,2,3,4,5]
z = np.array(l)

In [22]:
print(z.ndim)
z.shape

1


(5,)

In [26]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
Var = np.arange(2,10,2)
Var *= 3
print(Var)
Var = list(np.arange(2,10,2))
Var *= 3
print(Var)
# Broadcasting

[ 6 12 18 24]
[2, 4, 6, 8, 2, 4, 6, 8, 2, 4, 6, 8]


In [30]:
np.linspace(2,10,15)
# Includes end point number too

array([ 2.        ,  2.57142857,  3.14285714,  3.71428571,  4.28571429,
        4.85714286,  5.42857143,  6.        ,  6.57142857,  7.14285714,
        7.71428571,  8.28571429,  8.85714286,  9.42857143, 10.        ])

In [35]:
np.empty(100)

array([0.00000000e+000, 6.95170850e-310, 3.80924613e-321,             nan,
       1.50008929e+248, 6.99196220e+228, 2.59441754e+161, 1.16243294e-028,
       9.16281386e-072, 7.16535896e-090, 4.47593816e-091, 4.47593816e-091,
       4.47593816e-091, 4.47593816e-091, 4.47593816e-091, 4.47593816e-091,
       4.47593816e-091, 4.47593816e-091, 4.47593816e-091, 9.89803615e+164,
       6.58722068e+135, 1.43573466e-023, 2.07348683e+026, 1.42137878e-076,
       6.01390853e-154, 6.01347002e-154, 6.01347002e-154, 6.01347002e-154,
       5.36788236e+242, 1.63416450e-152, 4.70108394e+180, 1.17067659e+214,
       4.07702369e-144, 1.69593242e-152, 6.19941898e-071, 4.06986086e-066,
       3.94357072e+180, 9.89803615e+164, 2.95164329e-075, 7.13325665e-067,
       4.59657125e-072, 9.45956265e-076, 1.42137877e-076, 1.75621415e-023,
       2.95150849e-075, 5.30465689e+281, 1.91074908e+137, 5.68850135e-038,
       4.69589202e-085, 2.66263018e-061, 7.89212172e-114, 2.66263018e-061,
       9.48906829e+217, 9

In [45]:
np.sort(Var)

array([2, 2, 2, 4, 4, 4, 6, 6, 6, 8, 8, 8])

In [48]:
np.concatenate((a,z))

array([2, 4, 6, 8, 1, 2, 3, 4, 5])

In [55]:
k1 = np.array([[1,2],[3,4]])
k2 = np.array([[5,6],[7,8]])
print(np.concatenate((k1,k2),axis=0))
print(np.concatenate((k1,k2),axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [56]:
np.vstack((k1,k2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [60]:
bb = np.hstack((k1,k2))

In [58]:
k1+k2

array([[ 6,  8],
       [10, 12]])

In [59]:
k1.sum()

10

In [61]:
bb.sum(axis=0)

array([ 4,  6, 12, 14])

In [62]:
bb.sum(axis=1)

array([14, 22])

In [63]:
bb.min()

1

In [64]:
bb.max()

8

In [65]:
bb.sum(axis=0).min()

4

In [66]:
[1,2,33,4,]

[1, 2, 33, 4]

In [67]:
k1.transpose()

array([[1, 3],
       [2, 4]])

In [71]:
k1

array([[1, 2],
       [3, 4]])

In [72]:
np.flip(k1)

array([[4, 3],
       [2, 1]])

In [73]:
k1.flatten()

array([1, 2, 3, 4])